Update HaxeProperties.hx
Fix for:  
C:\\Users\\Matthew\\Downloads\\unihx-development\\unihx-development\\unihx\\_internal\\editor\\HaxeProperties.hx(13,46): error CS0266: Cannot implicitly convert type `object' to `UnityEngine.Vector2'. An explicit conversion exists (are you missing a cast?)